### ISSUE TITLE
compiling master serde_json error

### ISSUE THREAD

**Issue by forensicmatt** [jmespath/jmespath.rs#33]
serde_json errors when compiling master:

```
error[E0603]: enum `ErrorCode` is private
 --> src\variable.rs:9:32
  |
9 | use serde_json::error::{Error, ErrorCode};
  |                                ^^^^^^^^^
```
```
error[E0624]: method `syntax` is private
    --> src\variable.rs:1205:29
     |
1205 |             _ => return Err(Error::syntax(ErrorCode::KeyMustBeAString, 0, 0)),
     |                             ^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

**Comment by ms-ati** [comment]
Until a release is made, I found that adding the following lines to `Cargo.toml` will enable compiling with the latest `master` branch, which fixes this issue already:

```toml
[replace]
"jmespath:0.2.0" = { git = "https://github.com/jmespath/jmespath.rs" }
```

**Comment by davidB** [comment]
yes but you can not release/publish to crates.io, it's why I manually vendored the code into my crate (including update to edition 2018, I could made a PR if project's owner want it).

**Comment by forensicmatt** [comment]
This has been fixed in https://github.com/jmespath/jmespath.rs/commit/1ad855ce482908036cd46a9730ba70363c86218e for master. I am closing this issue.
