### ISSUE TITLE
CANARY ISSUE - Please acknowledge and close if seen by maintainer

### ISSUE THREAD

**Issue by ms-ati** [jmespath/jmespath.rs#35]
Hi all! Thanks so much for creating this crate.

Due to the current broken compilation against latest `serde_json` (see #33), please pardon me for creating this simple canary issue. It's simply a way to discover whether this crate has a maintainer who is engaged with Github.

If you are a maintainer, please do feel free to acknowledge, and simply close the issue!

Thanks again 😄

**Comment by cetra3** [comment]
Hey @ms-ati I have been provided maintainer of the project & will be looking to push a new version shortly which fixes this issue.

**Comment by kapilt** [comment]
a month+ after closing the canary issue, the last commit on the repo is still pre-pandemic...

**Comment by cetra3** [comment]
@kapilt The discussion is taking place in this PR: https://github.com/jmespath/jmespath.rs/pull/36, but that unfortunately removes some of the existing features.

If you'd like to include a smaller PR to address the current issues please go ahead
