### ISSUE TITLE
Add Cargo.lock to the repository

### ISSUE THREAD

**Issue by jirutka** [jmespath/jmespath.rs#47]
Can you please add Cargo.lock to the repository (and keep it up-to-date)? It’s important for Linux distributions packaging jmespath to achieve reproducible builds.

**Comment by cetra3** [comment]
I'm assuming this is just for the `jp` binary? Or are you talking about the library itself?

**Comment by jirutka** [comment]
The 'jp' binary. I've packaged it for Alpine Linux ([jp](https://pkgs.alpinelinux.org/packages?name=jp)).
