### ISSUE TITLE
Backticks support

### ISSUE THREAD

**Issue by arields1** [jmespath/jmespath.rs#51]
Hi, I'm new to rust so I might be missing something.
I was trying to use an expression with backticks:
```
locations[?state == `NY`].name
```

But got the following error:
```
JmespathError { offset: 20, line: 0, column: 20, expression: "locations[?state == `NY`].name|[0]", reason: Parse("Unable to parse literal JSON NY: expected value at line 1 column 1") }
```

Replacing the backticks with single quotes worked for me:
```
locations[?state == 'NY'].name
```

Adding escaped double quotes inside the backticks also worked:
```
locations[?state == `\"NY\"`].name
```

However, just backticks should also be supported.
Am I missing something?

```
extern crate jmespath;

fn main() {
    let expr = jmespath::compile("locations[?state == `NY`].name|[0]").unwrap();

    let json_str = r#"{"locations":[{"name":"Seattle","state":"WA"},{"name":"New York","state":"NY"},{"name":"Bellevue","state":"WA"},{"name":"Olympia","state":"WA"}]}"#;
    let data = jmespath::Variable::from_json(json_str).unwrap();

    let result = expr.search(data).unwrap();
    assert_eq!("New York", result.as_string().unwrap());
}
```

![image](https://github.com/jmespath/jmespath.rs/assets/82308911/8aea299d-491d-4a6e-b2e7-3633d0aadb9b)

**Comment by cetra3** [comment]
I have a feeling that the JSON literal does require what's inside the backticks to be valid json.

I.e, ``NY``

Which comes out as 
```
NY
```

is not valid json

But `"NY"`

Which comes out as

```
"NY"
```

is valid JSON.

In other words: I think the example on the website is too permissive.  In fact the specification gives examples with quotes (and other syntax) only: https://jmespath.org/specification.html#literal-expressions

**Comment by arields1** [comment]
You are right. It seems the implementation there is indeed too permissive.
Thanks!
